amarreapp/urls.py
from django.conf.urls import url
from django.views.i18n import set_language
from . import views
from .views import ListUsuarios, CreateUsuario, EditUsuario, DeleteUsuario
from .views import ListPrecios, CreatePrecio, EditPrecio, DeletePrecio
from .views import ListAmarres, CreateAmarre, EditAmarre, DeleteAmarre
from .views import ListDistancias, CreateDistancia, EditDistancia, DeleteDistancia
from .views import ListPuertos, CreatePuerto, EditPuerto, DeletePuerto
from .views import ListCombustibles, CreateCombustible, EditCombustible, DeleteCombustible
from .views import ListPredicciones, CreatePrediccion, EditPrediccion, DeletePrediccion
from .views import ListEmbarcaciones, CreateEmbarcacion, EditEmbarcacion, DeleteEmbarcacion

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^usuario$', ListUsuarios.as_view(), name='list_usuarios'),
    url(r'^usuario/create$', CreateUsuario.as_view(), name='create_usuario'),
    url(r'^usuario/edit/(?P<pk>\d+)/$', EditUsuario.as_view(), name='edit_usuario'),
    url(r'^usuario/delete/(?P<pk>\d+)/$', DeleteUsuario.as_view(), name='delete_usuario'),
    url(r'^usuario/edit/password/$', views.change_password, name='edit_password'),
    url(r'^precio$', ListPrecios.as_view(), name='list_precios'),
    url(r'^precio/create$', CreatePrecio.as_view(), name='create_precio'),
    url(r'^precio/edit/(?P<pk>\d+)/$', EditPrecio.as_view(), name='edit_precio'),
    url(r'^precio/delete/(?P<pk>\d+)/$', DeletePrecio.as_view(), name='delete_precio'),
    url(r'^amarre$', ListAmarres.as_view(), name='list_amarres'),
    url(r'^amarre/create$', CreateAmarre.as_view(), name='create_amarre'),
    url(r'^amarre/edit/(?P<pk>\d+)/$', EditAmarre.as_view(), name='edit_amarre'),
    url(r'^amarre/delete/(?P<pk>\d+)/$', DeleteAmarre.as_view(), name='delete_amarre'),
    url(r'^distancia$', ListDistancias.as_view(), name='list_distancias'),
    url(r'^distancia/create$', CreateDistancia.as_view(), name='create_distancia'),
    url(r'^distancia/edit/(?P<pk>\d+)/$', EditDistancia.as_view(), name='edit_distancia'),
    url(r'^distancia/delete/(?P<pk>\d+)/$', DeleteDistancia.as_view(), name='delete_distancia'),
    url(r'^amarre$', ListAmarres.as_view(), name='list_amarres'),
    url(r'^puerto$', ListPuertos.as_view(), name='list_puertos'),
    url(r'^puerto/create$', CreatePuerto.as_view(), name='create_puerto'),
    url(r'^puerto/edit/(?P<pk>\d+)/$', EditPuerto.as_view(), name='edit_puerto'),
    url(r'^puerto/delete/(?P<pk>\d+)/$', DeletePuerto.as_view(), name='delete_puerto'),
    url(r'^combustible$', ListCombustibles.as_view(), name='list_combustibles'),
    url(r'^combustible/create$', CreateCombustible.as_view(), name='create_combustible'),
    url(r'^combustible/edit/(?P<pk>\d+)/$', EditCombustible.as_view(), name='edit_combustible'),
    url(r'^combustible/delete/(?P<pk>\d+)/$', DeleteCombustible.as_view(), name='delete_combustible'),
    url(r'^prediccion$', ListPredicciones.as_view(), name='list_predicciones'),
    url(r'^prediccion/create$', CreatePrediccion.as_view(), name='create_prediccion'),
    url(r'^prediccion/edit/(?P<pk>\d+)/$', EditPrediccion.as_view(), name='edit_prediccion'),
    url(r'^prediccion/delete/(?P<pk>\d+)/$', DeletePrediccion.as_view(), name='delete_prediccion'),
    url(r'^embarcacion$', ListEmbarcaciones.as_view(), name='list_embarcaciones'),
    url(r'^embarcacion/create$', CreateEmbarcacion.as_view(), name='create_embarcacion'),
    url(r'^embarcacion/edit/(?P<pk>\d+)/$', EditEmbarcacion.as_view(), name='edit_embarcacion'),
    url(r'^embarcacion/delete/(?P<pk>\d+)/$', DeleteEmbarcacion.as_view(), name='delete_embarcacion'),
    url(r'^reserva$', views.search_mooring, name='search_mooring'),
]

amarres/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Interfaz administrativa
    url(r'^admin/', admin.site.urls),
    # Aplicacion Amarreapp 
    url(r'^$', include('amarreapp.urls')),
    url(r'^econavbalear/', include('amarreapp.urls')),
    # Django-registration-redux
    # gestion de login
    #url(r'^accounts/login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='auth_login'), 
    url(r'^accounts/', include('registration.backends.simple.urls')),
    # While in the registration.backends.default.urls it also provides 
    # the functions for activating the account in a two stage process:
    # url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

# The Django Registration Redux package provides the machinery for numerous
# functions. In the registration.backend.simple.urls, it provides:
#
#    registration -> /accounts/register/
#    registration complete -> /accounts/register/complete
#    login -> /accounts/login/
#    logout -> /accounts/logout/
#    password change -> /password/change/
#    password reset -> /password/reset/
#
#While in the registration.backends.default.urls it also provides the functions for activating the account in a two stage process:
#
#    activation complete (used in the two-step registration) -> activate/complete/
#    activate (used if the account actiona fails) -> activate/<activation_key>/
#    activation email (notifies the user an activation email has been sent out)
#
#            activation email body (a text file, that contains the activation email text)
#            activation email subject (a text file, that contains the subject line of the activation email)
#
#Now the catch. While Django Registration Redux provides all this functionality, it does not provide the templates. So we need to provide the templates associated with each view.
]

amarreapp/models.py
from decimal import Decimal 
from django.db import models
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext as _
from datetime import datetime, timedelta
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from .haversine import *


latitud_baleares = [degMinSec2Deg([38,40,30]),
                    degMinSec2Deg([40,5,48])]
longitud_baleares = [degMinSec2Deg([1,12,47]),
                    degMinSec2Deg([4,19,00])]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DNI = models.CharField(max_length=13, blank=False)
    gestor_puertos = models.BooleanField(blank = True, default=False)
    gestor_combustible = models.BooleanField(blank = True, default=False)
    gestor_predicciones = models.BooleanField(blank = True, default=False)


class Combustible(models.Model):
    TIPO_COMBUSTIBLE_CHOICES = (
        ('GASL', 'Gasoil'),
        ('GSLN', 'Gasolina'),
    )
    nombre = models.CharField(max_length=50, default = " ")
    tipo = models.CharField(
        max_length=4,
        choices=TIPO_COMBUSTIBLE_CHOICES,
        default='GASL',
    )
    precio_litro = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0.00)])
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)

    def __str__(self):
        return (('%s - %3.2f €/l' % (self.nombre, self.precio_litro)))


class Embarcacion(models.Model):
    TIPO_MOTOR_CHOICES = (
        ('I', 'Intraborda'),
        ('F', 'Fueraborda'),
    )
    nombre = models.CharField(max_length=50, default = " ")
    matricula = models.CharField(max_length=40, blank=True, default=" ")
    # Dimensiones fisicas de la embarcacion en metros con dos decimales
    eslora = models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(4.00), MaxValueValidator(15.99)])
    manga = models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(1.00), MaxValueValidator(5.99)])
    calado = models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(0.09), MaxValueValidator(3.99)])
    # Motores
    # TODO: En realidad esto deberia ser una relacion de N a 1 a una 
    # tabla de motores, es decir una embarcacion puede tener muchos motores
    # Numero de motores (1,2,3,4)
    motor_num = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)] 
    )
    # Cubicage del motor (centimetros cubicos o hp (horse power))
    motor_potencia = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)],
    )
    # Tipo_motor (Intra o Fora)
    motor_tipo = models.CharField(
        max_length=1,
        choices=TIPO_MOTOR_CHOICES,
        default='F',
    )
    # consumo regimen crucero (litros/hora)
    motor_consumo = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )
    # combustible (OneToOne)
    #motor_combustible = models.OneToOneField(Combustible, 
    motor_combustible = models.ForeignKey(Combustible, 
        null = True,
        default = None,
        on_delete = models.SET_NULL
    )
    # Velocidad de crucero en nudos (millas nauticas/hora)
    velocidad_kn = models.PositiveSmallIntegerField(default=1,
        validators=[MinValueValidator(1)],
        blank=False
    )
    # Propietario
    propietario = models.ForeignKey(User, 
        null=True, 
        default = None,
        on_delete=models.SET_NULL
    )
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)
    
    def __str__(self):
        return (self.nombre)


class Contacto(models.Model):
    domicilio = models.TextField(_('street'), blank=True)
    localidad = models.CharField(_('city'), max_length=200, blank=True)
    provincia = models.CharField(_('province'), max_length=200, blank=True)
    codigo_postal = models.CharField(_('postal code'), max_length=10, blank=True)
    pais = models.CharField(_('country'), max_length=100, blank=True)
    correo_electronico = models.EmailField(_('email'), blank=True)
    telefono_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    telefono = models.CharField(_('phone'), max_length=16, validators=[telefono_regex], blank=True)
    fax = models.CharField(max_length=16, validators=[telefono_regex], blank=True)
    url = models.URLField(blank=True)
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)

    def __str__(self):
        return "%s (%s)" % (self.localidad, self.domicilio)


class Precio(models.Model):
    nombre = models.CharField(_('name'),
        max_length=50, 
        default = " ")
    enero = models.DecimalField(_('January'), max_digits=5, decimal_places=2, default=10.00)
    febrero = models.DecimalField(_('February'), max_digits=5, decimal_places=2, default=10.00)
    marzo = models.DecimalField(_('March'), max_digits=5, decimal_places=2, default=10.00)
    abril = models.DecimalField(_('April'), max_digits=5, decimal_places=2, default=10.00)
    mayo = models.DecimalField(_('May'), max_digits=5, decimal_places=2, default=10.00)
    junio = models.DecimalField(_('June'), max_digits=5, decimal_places=2, default=10.00)
    julio = models.DecimalField(_('July'), max_digits=5, decimal_places=2, default=10.00)
    agosto = models.DecimalField(_('August'), max_digits=5, decimal_places=2, default=10.00)
    septiembre = models.DecimalField(_('September'), max_digits=5, decimal_places=2, default=10.00)
    octubre = models.DecimalField(_('October'), max_digits=5, decimal_places=2, default=10.00)
    noviembre = models.DecimalField(_('November'), max_digits=5, decimal_places=2, default=10.00)
    diciembre = models.DecimalField(_('December'), max_digits=5, decimal_places=2, default=10.00)
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)

    def __str__(self):
        return (self.nombre)


class Amarre(models.Model):
    nombre = models.CharField(_('name'),
        max_length=50, 
        default = " ")
    eslora = models.DecimalField(_('length'), max_digits=4, decimal_places=2)
    manga = models.DecimalField(_('beam'), max_digits=4, decimal_places=2)
    agua = models.BooleanField(_('water'), default=True)
    electricidad = models.BooleanField(_('electricity'), default=True)
    precio_dia = models.ForeignKey(Precio, 
        null = True,
        default = None,
        on_delete=models.SET_NULL)
    #puertos = models.ManyToManyField(Puerto)
    info = models.TextField(
         _('information'),
         max_length=160,
         blank=True
    )
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)

    def __str__(self):
        return (self.nombre + ',' + str(self.eslora) + 'x' + str(self.manga))


class Puerto(models.Model):
    TIPO_ISLA_CHOICES = (
        ('MA', 'Mallorca'),
        ('ME', 'Menorca'),
        ('IB', 'Ibiza'),
        ('FO', 'Formentera'),
    )
    nombre = models.CharField(_('name'),max_length=50, default = " ")
    # isla de las Islas Baleares 
    isla = models.CharField(_('island'),
        max_length=2,
        choices=TIPO_ISLA_CHOICES,
        default='MA',
    )
    # Coordenadas geograficas
    latitud = models.FloatField(_('latitude'), 
                                validators= [MinValueValidator(latitud_baleares[0]), MaxValueValidator(latitud_baleares[1])]
                               )
    longitud = models.FloatField(_('longitude'),
                                validators= [MinValueValidator(longitud_baleares[0]), MaxValueValidator(longitud_baleares[1])]
                               )
    #temporadas
    #amarres
    amarre = models.ManyToManyField(Amarre,
        null = True,
        blank = True,
        default = None
    )
    # Tiene rampa o no el puerto
    rampa = models.BooleanField(default=False)
    duchas = models.BooleanField(default=False)
    # Informacion adicional del puerto
    informacion = models.TextField(_('information'),
         max_length=160,
         blank=True
    )
    # Foto del puerto
    imagen = models.ImageField(_('image'), upload_to='images', blank=True, null=True)
    # Informacion de contacto del puerto (puede no tener)
    contacto = models.OneToOneField(Contacto, 
        null = True,
        blank = True,
        default = None,
        on_delete = models.SET_NULL
    )
    # Distancias a otros puertos
    distancias = models.ManyToManyField('self', through='Distancia', symmetrical=False)
    # Timestamp y updated (creado y modificado)
    timestamp = models.DateTimeField(_('TimeStamp'), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, auto_now_add=False)
    
    def __str__(self):
        return (self.nombre)


class Distancia(models.Model):
    #origen = models.OneToOneField(Puerto,
    origen = models.ForeignKey(Puerto,
        null = True,
        on_delete = models.SET_NULL,
        related_name=_('source')
    )    
    #destino = models.OneToOneField(Puerto,
    destino = models.ForeignKey(Puerto,
        null = True,

amarreapp/templates/amarre_add.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% trans 'Add Mooring' %}</h1>
  <form class="form-horizontal" method="post">
  {% csrf_token %}
    <div class="form-group">
      <label for="id_nombre" class="control-label col-sm-2 requiredField">{% trans 'Name' %}</label>
      <div class="col-sm-10">
        <input class="form-control" id="id_nombre" maxlength="50" name="nombre" type="text" value="" required /> 
      </div>
    </div>
    <div class="form-group">
      <label for="id_eslora" class="control-label col-sm-2 requiredField">{% trans 'Length' %}</label>
      <div class="col-sm-2">
        <input class="form-control" id="id_eslora" name="eslora" type="number" step="0.01" min="3.50" max="12.00" required /> 
      </div>
      <label for="id_manga" class="control-label col-sm-2 requiredField">{% trans 'Beam' %}</label>
      <div class="col-sm-2">
        <input class="form-control" id="id_manga" name="manga" type="number" step="0.01" min="0.50" max="4.00" required /> 
      </div>
      <div class="col-sm-2">
        <div class="checkbox">
          <label><input type="checkbox" name="agua" class="checkbox col-sm-2"> {% trans 'Water' %}</label>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="checkbox">
          <label><input type="checkbox" name="electricidad" class="checkbox col-sm-2"> {% trans 'Electricity' %}</label>
        </div>
      </div>
    </div>
    <div class="form-group">
    </div>
         <div class="panel panel-default">
           <div class="panel-heading">{% trans 'Price' %}</div>
             <div class="table-responsive">                                 
               <table class="table table-striped">                                
                <thead> 
		 <tr>
		   <th></th>
		   <th>{% trans 'Name' %}</th>
		   <th>{% trans 'Jan' %}</th>
		   <th>{% trans 'Feb' %}</th>
		   <th>{% trans 'Mar' %}</th>
		   <th>{% trans 'Apr' %}</th>
		   <th>{% trans 'May' %}</th>
		   <th>{% trans 'Jun' %}</th>
		   <th>{% trans 'Jul' %}</th>
		   <th>{% trans 'Aug' %}</th>
		   <th>{% trans 'Sep' %}</th>
		   <th>{% trans 'Oct' %}</th>
		   <th>{% trans 'Nov' %}</th>
		   <th>{% trans 'Dec' %}</th>
		   <th></th>
		   <th></th>
		 </tr>
                </thead>
                <tbody>
		 {% for precio in list_precios %}
		 <tr>
                     <td>
		       <input type="radio" name="opcionPrecio" id="opcionPrecio" value={{precio.id}} required> 
		     </td>
		     <td>{{ precio.nombre}}</td>
		     <td>{{ precio.enero }}</td>
		     <td>{{ precio.febrero}}</td>
		     <td>{{ precio.marzo }}</td>
		     <td>{{ precio.abril }}</td>
		     <td>{{ precio.mayo }}</td>
		     <td>{{ precio.junio }}</td>
		     <td>{{ precio.julio }}</td>
		     <td>{{ precio.agosto}}</td>
		     <td>{{ precio.septiembre }}</td>
		     <td>{{ precio.octubre }}</td>
		     <td>{{ precio.noviembre }}</td>
		     <td>{{ precio.diciembre}}</td>
		     <td>
		       <a class="related-widget-wrapper-link change-related" id="change_id_precio"
			  href="{% url 'edit_precio' pk=precio.id %}?amp;_popup=1"
			  title="{% trans 'Change selected price' %}">
			 <img src="/static/admin/img/icon-changelink.svg" alt="{% trans 'Change' %}"/>
		       </a>
		     </td>
		     <td>
		       <a class="related-widget-wrapper-link delete-related" id="delete_id_precio"
			  href="{% url 'delete_precio' pk=precio.id %}?&amp;_popup=1"
			  title="{% trans 'Delete selected price' %}">
			 <img src="/static/admin/img/icon-deletelink.svg" alt="{% trans 'Delete' %}"/>
		       </a>
		      </td>
		 </tr>
		 {% endfor %}
                </tbody>
               </table>
	       <a class="btn btn-primary btn-block" id="add_id_precio"
	          href="{% url 'create_precio' %}?&amp;_popup=1"
	          title="{% trans 'Add Price' %}">
	          {% trans 'Add Price' %}
	       </a>
             </div>
         </div>
    <div class="form-group">
      <button class="btn btn-primary btn-block"  align="center" 
        type="submit" name="order" value="Save">
	{% trans 'Save' %}
      </button>
    </div>
  </form>
{% endblock %}

amarreapp/templates/combustibles.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% trans 'Fuel' %}</h1>
    {% if object_list %}
    <div class="table-responsive">                                 
    <table class="table table-striped">                                 
      <tr>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Type" %}</th>
        <th>{% trans "Price €/l" %}</th>
        <th>{% trans "Date" %}</th>
        <th></th></tr>
      {% for combustible in object_list %}
      <tr>
        <td>{{ combustible.nombre }}</td>
        <td>{{ combustible.tipo}}</td>
        <td>{{ combustible.precio_litro}}</td>
        <td>{{ combustible.updated }}</td>
        <td>
	  {% if perms.amarreapp.change_combustible %}
	  <a class="related-widget-wrapper-link change-related" id="change_id_precio"
	     href="{% url 'edit_combustible' pk=combustible.id %}?amp;_popup=1"
	     title="{% trans 'Change selected fuel' %}">
	    <img src="/static/admin/img/icon-changelink.svg" alt="{% trans 'Change' %}"/>
	  </a>
	  {% endif %}
	  {% if perms.amarreapp.delete_combustible %}
	  <a class="related-widget-wrapper-link delete-related" id="delete_id_precio"
	     href="{% url 'delete_combustible' pk=combustible.id %}?&amp;_popup=1"
	     title="{% trans 'Delete selected fuel' %}">
	    <img src="/static/admin/img/icon-deletelink.svg" alt="{% trans 'Delete' %}"/>
	  </a>
	  {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>      
    </div>      
    {% else %}
    {% endif %}
    {% if perms.amarreapp.add_combustible %}
    <form role="form" id="combustibles_form" method="post" action="{% url 'list_combustibles' %}">
    {% csrf_token %}
	  <button class="btn btn-primary btn-block"  align="center" 
		  type="submit" name="order" value="add">
	    {% trans 'Add' %}
	  </button>
    </form>
    {% endif %}
{% endblock %}

amarreapp/templates/usuario_add.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{% trans 'Add User' %}</h1>
  <form class="form-horizontal" method="post">
  {% csrf_token %}
    <div class="form-group">
      <span style="color: red;">{{ form.username.errors }} </span>
      <label for="id_username" class="control-label col-sm-2 requiredField">{% trans "Username" %}</label>
      <div class="col-sm-10">
        <input class="form-control" id="id_username" maxlength="150" name="username" type="text"
	value=
	{% if form.username.value %}
	  {{ form.username.value }}
	{% else %}
	  ""
	{% endif %} required /> 
      </div>
    </div>
    <div class="form-group">
      <span style="color: red;">{{ form.password1.errors }} </span>
      <label for="id_password1" class="control-label col-sm-2 requiredField">{% trans "Password" %}</label>
      <div class="col-sm-10">
        <input class="form-control" id="id_password1" name="password1" type="password" required />
      </div>
    </div>
    <div class="form-group">
      <span style="color: red;">{{ form.password2.errors }} </span>
      <label for="id_password2" class="control-label col-sm-2 requiredField">{% trans "Password (Confirm)" %}</label>
      <div class="col-sm-10">
        <input class="form-control" id="id_password2" name="password2" type="password" required />
      </div>
    </div>
    <div class="form-group">
      <span style="color: red;">{{ form.first_name.errors }} </span>
      <span style="color: red;">{{ form.last_name.errors }} </span>
      <label for="id_first_name" class="control-label col-sm-2 requiredField">{% trans "First Name" %}</label>
      <div class="col-sm-2">
        <input class="form-control" id="id_first_name" name="first_name" type="text" maxlength="30" 
	value=
        {% if form.first_name.value %}
	  {{ form.first_name.value }}
        {% else %}
          ""
        {% endif %} required /> 
      </div>
      <label for="id_last_name" class="control-label col-sm-2 requiredField">{% trans "Last Name" %}</label>
      <div class="col-sm-6">
        <input class="form-control" id="id_last_name" name="last_name" type="text" maxlength="30"
	value=
        {% if form.last_name.value %}
	  {{ form.last_name.value }}
        {% else %}
          ""
        {% endif %} required /> 
      </div>
    </div>
    <div class="form-group">
      <span style="color: red;">{{ form.email.errors }} </span>
      <label for="id_email" class="control-label col-sm-2 requiredField">{% trans "E-mail" %}</label> 
      <div class="col-sm-6">
        <input class="form-control" id="id_email" maxlength="254" name="email" type="email" 
          value={% if form.email.value %} {{form.email.value}} {% else %} "" {% endif %} required/>
      </div>
    </div>
    <div class="form-group">
      <span style="color: red;">{{ form.is_superuser.errors }} </span>
      <div class="checkbox-row col-sm-offset-2 col-sm-2">
        {{ form.is_superuser }}
        <label for="id_is_superuser" class="vCheckboxLabel">{% trans "Is superuser" %}</label>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">{% trans "Profile" %}</div>
      <div class="panel-body">
        <div class="form-group">
          <span style="color: red;">{{ form.DNI.errors }} </span>
          <label for="id_DNI" class="control-label col-sm-2 requiredField">DNI</label> 
          <div class="col-sm-6">
            <input id="id_DNI" maxlength="13" name="DNI" type="text" class="form-control" 
              value={% if form.DNI.value %} {{form.DNI.value}} {% else %} "" {% endif %}/>
          </div>
        </div>
        <div class="form-group">
          <span style="color: red;">{{ form.gestor_puertos.errors }} </span>
          <span style="color: red;">{{ form.gestor_combustible.errors }} </span>
          <span style="color: red;">{{ form.gestor_predicciones.errors }} </span>
	  <label for="id_groups" class="control-label col-sm-2">{% trans "Groups:" %}</label>
          <div class="checkbox-row col-sm-6">
            {{ form.gestor_puertos }}
            <label for="id_gestor_puertos" class="vCheckboxLabel"> {% trans "Port manager" %}</label>
          </div>
        </div>
        <div class="form-group">
          <div class="checkbox-row col-sm-offset-2 col-sm-6">
            {{ form.gestor_combustible }}
            <label for="id_gestor_combustible" class="vCheckboxLabel">{% trans "Fuel Manager" %}</label>
          </div>
        </div>
        <div class="form-group">
          <div class="checkbox-row col-sm-offset-2 col-sm-6">
            {{ form.gestor_predicciones }}
            <label for="id_gestor_predicciones" class="vCheckboxLabel">{% trans "Forecast manager" %}</label>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <button class="btn btn-primary btn-block" align="center"
              type="submit" name="order" value="Save">
        {% trans 'Save' %}
      </button>
    </div>
  </form>
{% endblock %}